# Generated by Django 5.0.3 on 2024-03-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Курс', 'verbose_name_plural': 'Курсы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Урок', 'verbose_name_plural': 'Уроки'},
        ),
        migrations.AlterModelOptions(
            name='tasks',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AddField(
            model_name='courses',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок курса'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default=None, max_length=50, verbose_name='Заголовок урока'),
        ),
    ]
