# Generated by Django 5.0.3 on 2024-03-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_courses_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='description',
            field=models.TextField(default='Описание', max_length=500, verbose_name='Описание курса'),
        ),
    ]
