# Generated by Django 5.0.3 on 2024-04-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_courses_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='poster',
            field=models.ImageField(default='poster.png', upload_to='posters', verbose_name='Постер для видео'),
        ),
    ]
