# Generated by Django 5.0.3 on 2024-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_lesson_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='hide',
            field=models.BooleanField(default=True, verbose_name='Режим отладки'),
        ),
    ]
