# Generated by Django 5.0.3 on 2024-06-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_courses_hide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dossing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dossing_list', models.TextField(max_length=10000, verbose_name='Список дозировок')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
