# Generated by Django 5.0.3 on 2024-03-13 06:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestConsultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта отправителя')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('country', models.CharField(max_length=50, verbose_name='Страна проживания')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос на консультацию',
                'verbose_name_plural': 'Запросы на консультацию',
            },
        ),
    ]
